name: Running tests
on:
  workflow_dispatch:
  push:

env:
  MIX_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: '24.x'
          elixir-version: '1.12.x'

      - name: Install dependencies
        run: mix deps.get

      - name: Compile
        run: mix compile

      - name: Run tests
        run: mix test
